import requests
import random

SOURCE = "https://poetrydb.org/title/"
TITLES = [
    " Thoughts On The Works Of Providence",
    "\"All Is Vanity, Saith the Preacher\"",
    "\"And the sins of the fathers shall be\"",
    "\"Arcturus\" is his other name",
    "\"By the Waters of Babylon.\"",
    "\"De Gustibus--\"",
    "\"Faith\" is a fine invention",
    "\"Faithful to the end\" Amended",
    "\"Heaven\" -- is what I cannot reach!",
    "\"Heaven\" has different Signs -- to me --",
    "\"Heavenly Father\" -- take to thee",
    "\"Home\"",
    "\"Hope\" is the thing with feathers",
    "\"I have heard the sunset song of the birches,\"",
    "A Boston Ballad, 1854.",
    "A Bridal Song",
    "A COUNTRY LIFE:TO HIS BROTHER, MR THOMAS HERRICK",
    "A Calendar of Sonnets: April",
    "A Calendar of Sonnets: January",
    "A Calendar of Sonnets: July",
    "A loss of something ever felt I --",
    "A man went before a strange God",
    "A poem on divine revelation",
    "A poem, on the rising glory of America",
    "A soft Sea washed around the House",
    "A something in a summer's Day",
    "A spirit sped",
    "Imitated From Catullus. to Ellen",
    "Imitation of Tibullus. Sulpicia AD Cerinthum (Lib. Quart.)",
    "Immured in Heaven!",
    "Impromptu",
    "Impromptu, in Reply to a Friend",
    "In Drear-Nighted December",
    "In Former Songs.",
    "Oh! Think Not My Spirits Are Always As Light",
    "Oh! Weep for Those",
    "Oh, They have Robbed Me of The Hope",
    "Old Man",
    "On A Portrait Of Wordsworth",
    "On An Eclipse Of The Moon",
    "On Another's Sorrow",
    "On Being Asked What Was the \"Origin of Love.\"",
    "On Death",
    "Sonnet IX: As Other Men",
    "Sonnet LII: What? Dost Thou Mean",
    "Sonnet LIII: Clear Anker",
    "Sonnet LIV: Yet Read at Last",
    "Sonnet LIX: As Love and I",
    "Sonnet LVI: When Like an Eaglet",
    "Sonnet LVIII: In Former Times",
    "Sonnet LXI: Since There's No Help",
    "Sonnet LXII: When First I Ended",
    "Sonnet Reversed",
    "Sonnet VII: Love in a Humour",
    "Sonnet VII: When Nature",
    "Sonnet VIII: There's Nothing Grieves Me",
    "Sonnet X: Dang'rous to Hear",
    "Sonnet X: To Nothing Fitter",
    "Sonnet XI: You Not Alone",
    "Sonnet XII: That Learned Father",
    "The Canterbury Tales. The Reeve's Tale.",
    "The Canterbury Tales. The Second Nun's Tale",
    "The Canterbury Tales. The Shipman's Tale.",
    "The Canterbury Tales. The Sompnour's Tale.",
    "The Canterbury Tales. The Squire's Tale.",
    "The Canterbury Tales. The Wife of Bath's Tale.",
    "The Captive's Dream",
    "The Castle of Mains",
    "The Cathedral of Rheims",
    "The Cellar Door",
    "The Cenci.  a Tragedy in Five Acts",
    "The Chain I Gave.  From the Turkish",
    "The Sea-Child",
    "The Seasons: Winter",
    "The Sensitive Plant",
    "The Service without Hope --",
    "The Sheiling",
    "The Shepheardes Calender: April",
    "The Shepherd",
    "The Shepherd's Dog",
    "The Shepherd's Tree",
    "The Sick Rose",
    "The Siege of Corinth",
    "Up at a Villa--Down in the City",
    "Upon Appleton House, to My Lord Fairfax",
    "Upon My Dear and Loving Husband his Going into England Jan. 16",
    "Upon The Hill And Grove At Bill-borow",
    "Upon the Priory Grove, His Usual Retirement",
    "Upon the road of my life",
    "Upon the saying that my VERSES were made by another.",
    "V. The Soldier",
    "Variation of the Song of the Moon",
    "Venice. a Fragment",
    "Verses Found in a Summer-House at Hales-Owen",
    "Verses On A Butterfly",
    "Verses on a Cat",
    "Verses on the Death of Doctor Swift",
    "Versicles",
    "Victoria",
    "Vision Of The Archangels, The",
    "Vision of Belshazzar",
    "WHY FLOWERS CHANGE COLOUR",
    "Youth and Art",
    "Zummer An' Winter",
    "from Jubilate Agno, Fragment B, lines 695-768"
]


def get_random():
    url = "%s%s" % (SOURCE, random.choice(TITLES))
    r = requests.get(url)
    poems = r.json()
    index = random.randint(0, len(poems) - 1)
    lines = "\n".join(poems[index]["lines"])
    return {
        "title": poems[index]["title"],
        "author": poems[index]["author"],
        "poem": lines
    }
